{{ config(materialized='table') }}

SELECT
    CAST(ORDER_DATE AS DATE) AS SALES_DATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(TOTAL_AMOUNT) AS AVERAGE_ORDER_VALUE
FROM {{ ref('fact_sales') }}
GROUP BY CAST(ORDER_DATE AS DATE)
ORDER BY SALES_DATE
